export const BURGER_CONSTRUCTOR_ADD = 'BURGER_CONSTRUCTOR_ADD';
export const BURGER_CONSTRUCTOR_DELETE = 'BURGER_CONSTRUCTOR_DELETE';
export const BURGER_CONSTRUCTOR_CLEAR = 'BURGER_CONSTRUCTOR_CLEAR';
export const BURGER_CONSTRUCTOR_SORT = 'BURGER_CONSTRUCTOR_SORT';
